# Tensor Basics: answers

In [1]:
# import libraries
import torch
import numpy as np

## Creating tensors

In [2]:
# Exercise 1 solution
tensor_exercise1 = torch.arange(1, 11)
print("Exercise 1 solution:\n", tensor_exercise1)

# Exercise 2 solution
tensor_exercise2 = torch.eye(3)
print("\nExercise 2 solution:\n", tensor_exercise2)

Exercise 1 solution:
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Exercise 2 solution:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


##  Operations with tensors

In [3]:
# Exercise 3 solution:

# Given this tensor:
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

# Compute the mean and standard deviation
mean = torch.mean(x)
std = torch.std(x)

# Normalize the tensor by subtracting the mean and dividing by the standard deviation
normalized_x = (x - mean) / std

# Print the normalized tensor
print(normalized_x)

tensor([-1.2649, -0.6325,  0.0000,  0.6325,  1.2649])


In [4]:
# Exercise 4 solution:

# Create the input tensors
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])

# Concatenate tensors along the rows (dimension 0)
concatenated_tensor = torch.cat((x, y), dim=0)

# Print the concatenated tensor
print(concatenated_tensor)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [5]:
# Exercise 5 solution:

# Create a tensor with dimensions (2, 2, 2) filled with random values
x = torch.randn((2, 2, 2))
print(x)

# Compute the sum of all elements
sum_of_elements = x.sum()

# Print the result
print(sum_of_elements)

tensor([[[-1.4353, -1.2890],
         [ 0.4348,  1.0837]],

        [[ 0.5278,  0.8892],
         [-0.4966, -1.0028]]])
tensor(-1.2882)


# Manipulating tensor shapes

In [6]:
# Exercise 6 solution:
# Create the tensor with dimensions (2, 3, 4, 5)
tensor = torch.arange(120).reshape(2, 3, 4, 5)
print("Original Tensor Shape:", tensor.shape)

# Reshape the tensor to have one less dimension using -1
reshaped_tensor = tensor.reshape(2, 3, -1)
print("Reshaped Tensor Shape:", reshaped_tensor.shape)

Original Tensor Shape: torch.Size([2, 3, 4, 5])
Reshaped Tensor Shape: torch.Size([2, 3, 20])


#  Moving tensors from CPU to GPU and vice versa

In [7]:
# Exercise 7 solution:
# Step 1: Create a tensor on the CPU
x = torch.randn((3, 3))

# Step 2: Move the tensor to the GPU
x = x.to("cuda") # x = x.cuda()

# Step 3: Print the device attribute of x (GPU)
print("Device of x (after moving to GPU):", x.device)

# Step 4: Move the tensor back to the CPU
x = x.to("cpu") # x = x.cpu()

# Step 5: Print the device attribute of x (CPU)
print("Device of x (after moving back to CPU):", x.device)

Device of x (after moving to GPU): cuda:0
Device of x (after moving back to CPU): cpu
