# Tensor Basics: Examples and exercises
This section covers:
* Creating tensors (from scratch and from previous data)
* Accessing tensor properties
* Basic operations with tensors
* Manipulating tensor shapes
* Moving tensors from CPU to GPU and vice versa

In [1]:
# import libraries
import torch
import numpy as np

# 1. Creating Tensors

In [3]:
# Tensor from list
my_list = [1, 4, 6, 8]
tensor_from_list = torch.tensor(my_list)
print("Tensor from data:\n", tensor_from_list)

# Tensor from NumPy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_numpy = torch.from_numpy(numpy_array) # tensor_from_numpy = torch.tensor(numpy_array)
print("\nTensor from NumPy array:\n", tensor_from_numpy)

# NumPy array from tensor
my_tensor = torch.tensor([[7, 8, 9], [10, 11, 12]])
numpy_from_tensor = my_tensor.numpy()
print("\nNumPy array from Tensor:\n", numpy_from_tensor)

# Tensor filled with zeros with specific shape and data type
shape = (2,2)
dtype = torch.float64
tensor_with_shape_and_dtype = torch.zeros(shape, dtype = dtype)
print("\nTensor filled with zeros:\n", tensor_with_shape_and_dtype)

Tensor from data:
 tensor([1, 4, 6, 8])

Tensor from NumPy array:
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

NumPy array from Tensor:
 [[ 7  8  9]
 [10 11 12]]

Tensor filled with zeros:
 tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


<h2 align="center"><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
<table align="center">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

## Reproducibility
While randomness can be powerful, there are instances when having less randomness is preferable. The reason behind this is to enable the replication of experiments. This becomes especially important when, for instance, you design an algorithm that achieves a certain level of performance, and you want your colleague to test it out to confirm its validity.

But how can they do this? This is where reproducibility becomes essential. In essence, reproducibility refers to the ability to obtain similar or identical results on different computers running the same code.

To illustrate reproducibility in PyTorch, let's consider a brief example. We begin by generating two random tensors. Since they are created randomly, it is expected that they would differ from each other.

In [4]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B?")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1025, 0.6321, 0.8880, 0.7968],
        [0.6356, 0.3658, 0.6410, 0.5889],
        [0.2237, 0.6439, 0.4582, 0.1804]])

Tensor B:
tensor([[0.4570, 0.5917, 0.2936, 0.6991],
        [0.4074, 0.1554, 0.4737, 0.0532],
        [0.2042, 0.1962, 0.0119, 0.8157]])

Does Tensor A equal Tensor B?


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Just as you might've expected, the tensors come out with different values. But what if you wanted to create two random tensors with the same values?
That's where [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) comes in, where `seed` is an integer (like `42` but it could be anything).

In [5]:
# Set the random seed
RANDOM_SEED = 42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed = RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed = RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D?")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

> **Resource:**  If you need additional information about reproducbility and random seeds, check out:
> * [The PyTorch reproducibility documentation](https://pytorch.org/docs/stable/notes/randomness.html)

### Exercise 1: Create a tensor with values ranging from 1 to 10 (inclusive) and print it. Hint: Use [torch.arange()](https://pytorch.org/docs/stable/generated/torch.arange.html)

In [4]:
# Wite your code here

Exercise 1 solution:
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


### Exercise 2: Returns a 2-D tensor of size (3,3) with ones on the diagonal and zeros elsewhere. Hint: Use [torch.eye()](https://pytorch.org/docs/stable/generated/torch.eye.html)

In [9]:
# Wite your code here


Exercise 2 solution:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# 2. Accessing Tensor Properties

In [6]:
# Create a sample tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Print some interesting attribute of the tensor
print("Data type:", tensor.dtype)
print("Shape:", tensor.shape)
print("Stride:", tensor.stride())
print("Number of dimensions:", tensor.dim())
print("Number of elements:", tensor.numel())
print("Requires gradient?", tensor.requires_grad)
print("Device:", tensor.device)
print("Requires grad computation:", tensor.requires_grad)

Data type: torch.int64
Shape: torch.Size([2, 3])
Stride: (3, 1)
Number of dimensions: 2
Number of elements: 6
Requires gradient? False
Device: cpu
Requires grad computation: False



<h3 align="center">Classification of tensors by their dimensions</h3>

| Name | What is it? | Number of dimensions 
| ----- | ----- | ----- | 
| **scalar** | a single number | 0 
| **vector** | a 1-dimensional array of numbers | 1 |
| **matrix** | a 2-dimensional array of numbers | 2 
| **tensor** | an n-dimensional array of numbers | can be any number from 0

# 3.  Operations with tensors

In [7]:
# Element-wise addition
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor_sum = tensor1 + tensor2
print("Element-wise addition:\n", tensor_sum)

# Scalar multiplication
scalar = 2
tensor_scaled = tensor1 * scalar
print("\nScalar multiplication:\n", tensor_scaled)

# Matrix multiplication
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])
matrix_product = torch.matmul(matrix1, matrix2)
print("\nMatrix multiplication:\n", matrix_product)

# Automatic Differentiation
x = torch.tensor(2.0, requires_grad = True)
y = x**2 + 3*x + 1
y.backward() 
print("\nGradient of y with respect to x:", x.grad)

# y.backward: It calculates the gradients of y with respect to all the tensors that have requires_grad = True. 
# In this case, it computes the gradient of y with respect to x.

Element-wise addition:
 tensor([5, 7, 9])

Scalar multiplication:
 tensor([2, 4, 6])

Matrix multiplication:
 tensor([[19, 22],
        [43, 50]])

Gradient of y with respect to x: tensor(7.)


### Exercise 3: Normalizing a PyTorch Tensor: [mean()](https://pytorch.org/docs/stable/generated/torch.mean.html#torch.mean) and [std()](https://pytorch.org/docs/stable/generated/torch.std.html#torch.std) functions

In [ ]:
# Given this tensor:
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

# Compute the mean and standard deviation: Hint: use mean() and std() functions
mean = # Fill this
std =  # Fill this

# Normalize the tensor by subtracting the mean and dividing by the standard deviation
normalized_x = # Fill this

# Print the normalized tensor
# Fill this

### Exercise 4: Concatenate tensors using [cat()](https://pytorch.org/docs/stable/generated/torch.cat.html) function

In [ ]:
# Create two input tensors of size (2, 3) with your desired values.
x = # Fill
y = # Fill

# Concatenate tensors along the rows (dimension 0)
# Fill

# Print the concatenated tensor
# Fill

### Exercise 5: Compute the sum of all elements in a tensor using [sum()](https://pytorch.org/docs/stable/generated/torch.sum.html) function

In [ ]:
# Create a tensor with dimensions (2, 2, 2) filled with random values
# Fill

# Compute the sum of all elements
# Fill

# Print the result
# Fill

## 4. Manipulating tensor shapes

Often times we'll want to reshape or change the dimensions of our tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible). |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 

### Example 1: Reshaping using [view()](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html)

In [9]:
# Create a tensor with values from 0 to 23
tensor = torch.arange(24)
print("Original Tensor:")
print(tensor)

# Reshape to dimensions (2, 3, 4)
print("\nReshaped Tensor using view():")
reshaped_tensor = tensor.view(2, 3, 4)
print(reshaped_tensor)

# Reshape to dimensions (6, 4)
print("\nReshaped Tensor using view():")
reshaped_tensor = tensor.view(6, 4) 
print(reshaped_tensor)
print()

Original Tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Reshaped Tensor using view():
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Reshaped Tensor using view():
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])



### Example 2: Reshaping using [squeeze()](https://pytorch.org/docs/stable/generated/torch.squeeze.html)

torch.squeeze() returns a tensor with all specified dimensions of input of size 1 removed.To do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [10]:
# Create a tensor with dimensions (3, 1, 5)
tensor = torch.rand(3, 1, 5)
print("Original Tensor:")
print(tensor)
print("\nOriginal Tensor Shape:",tensor.shape)

print("\n----------------------SQUEEZE------------------------")

print("Reshaped Tensor using squeeze():")
reshaped_tensor = tensor.squeeze()  # Remove dimensions with size 1
print(reshaped_tensor)
print("\nReshaped Tensor Shape:",reshaped_tensor.shape)

print("\n----------------------UNSQUEEZE----------------------")

print("Recovered Tensor using unsqueeze():")
recovered_tensor = reshaped_tensor.unsqueeze(dim = 1)
print(recovered_tensor)
print("\nRecovered Tensor Shape:",recovered_tensor.shape)

Original Tensor:
tensor([[[0.8694, 0.5677, 0.7411, 0.4294, 0.8854]],

        [[0.5739, 0.2666, 0.6274, 0.2696, 0.4414]],

        [[0.2969, 0.8317, 0.1053, 0.2695, 0.3588]]])

Original Tensor Shape: torch.Size([3, 1, 5])

----------------------SQUEEZE------------------------
Reshaped Tensor using squeeze():
tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854],
        [0.5739, 0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695, 0.3588]])

Reshaped Tensor Shape: torch.Size([3, 5])

----------------------UNSQUEEZE----------------------
Recovered Tensor using unsqueeze():
tensor([[[0.8694, 0.5677, 0.7411, 0.4294, 0.8854]],

        [[0.5739, 0.2666, 0.6274, 0.2696, 0.4414]],

        [[0.2969, 0.8317, 0.1053, 0.2695, 0.3588]]])

Recovered Tensor Shape: torch.Size([3, 1, 5])


### Exercise 6: Reshape a tensor using [reshape()](https://pytorch.org/docs/stable/generated/torch.reshape.html)

In [12]:
# Create the tensor with dimensions (2, 3, 4, 5)
tensor = torch.arange(120).reshape(2, 3, 4, 5)
print("Original Tensor Shape:", tensor.shape)

# Reshape the tensor to have one less dimension (using -1) and print the new dimensions
# Fill

Original Tensor Shape: torch.Size([2, 3, 4, 5])
Reshaped Tensor Shape: torch.Size([2, 3, 20])


## 5. Moving tensors from CPU to GPU and vice versa

**Be careful!**: When you call tensor.to(device) to transfer a tensor to a specific device (e.g., GPU), it **doesn't modify the original tensor in-place**. Instead, it returns a **new tensor** that resides on the specified device. However, if you directly print the tensor after calling tensor.to(device), it will still display the tensor's original location, which is the CPU.

In [13]:
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create a tensor (in cpu)
tensor = torch.tensor([1, 2, 3])
print(f"Tensor on CPU:{tensor} and device: {tensor.device}")

# Move tensor to cuda if available? -> WRONG
tensor.to(device)
print(f"Tensor on CPU:{tensor} and device: {tensor.device}")

# Move tensor to cuda if available-> RIGHT
tensor_gpu = tensor.to(device)
print(f"Tensor on GPU:{tensor_gpu} and device: {tensor_gpu.device}")

# Create a tensor in GPU directly
tensor = torch.tensor([1, 2, 3], device = device )
print(f"Tensor on GPU:{tensor} and device: {tensor.device}")

Tensor on CPU:tensor([1, 2, 3]) and device: cpu
Tensor on CPU:tensor([1, 2, 3]) and device: cpu
Tensor on GPU:tensor([1, 2, 3], device='cuda:0') and device: cuda:0
Tensor on GPU:tensor([1, 2, 3], device='cuda:0') and device: cuda:0


### Exercise 7: GPU/CPU

Imagine that cuda is available: **torch.cuda.is_available() = True** (Don't need to check this attribute)

In [14]:
# Step 1: Create a tensor on the CPU


# Step 2: Move the tensor to the GPU


# Step 3: Print the device attribute 


# Step 4: Move the tensor back to the CPU


# Step 5: Print the device attribute 


Device of x (after moving to GPU): cuda:0
Device of x (after moving back to CPU): cpu
